// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecomerce.infrsutractor.Data;

#nullable disable

namespace ecomerce.infrsutractor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405103550_test1")]
    partial class test1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ecomerce.domain.entity.Catogry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("catogries");
                });

            modelBuilder.Entity("ecomerce.domain.entity.Proudct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatogryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Describition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("qualty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatogryId");

                    b.ToTable("proudcts");
                });

            modelBuilder.Entity("ecomerce.domain.entity.Proudct", b =>
                {
                    b.HasOne("ecomerce.domain.entity.Catogry", "catogry")
                        .WithMany("proudcts")
                        .HasForeignKey("CatogryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("catogry");
                });

            modelBuilder.Entity("ecomerce.domain.entity.Catogry", b =>
                {
                    b.Navigation("proudcts");
                });
#pragma warning restore 612, 618
        }
    }
}
