<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.14">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Stripe.net" Version="46.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\ecommerce.application.csproj" />
    <ProjectReference Include="..\ClassLibrary2\ecommerce.application.csproj" />
    <ProjectReference Include="..\ClassLibrary3\ecomerce.infrsutractor.csproj" />
    <ProjectReference Include="..\Infrastructure\ecomerce.infrsutractor.csproj" />
  </ItemGroup>

</Project>
